alias v='/usr/local/bin/mvim -v'
alias vim='/usr/local/bin/mvim -v'
alias vimrc='vim ~/.vimrc'

alias @deploy='ssh -t bot "sudo su - deploy"'
alias @honey='ssh honey'
alias @mango='ssh mango'
alias abort="git unstage;gca;gcf;git rebase --abort;"
alias abort="git unstage;gca;gcf;git rebase --abort;"
alias active="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"
alias aliases="vim ~/source/dotfiles/profile/aliases.zsh"
alias b="bundle"
alias be="bundle exec"
alias be="bundle exec"
alias bi="b install --path vendor"
alias binc="bundle install --no-cache"
alias binit="bi && bp"
alias bl="bundle list"
alias bomb="rm -rf vendor/javascripts;bower install;gcbw"
alias bp="bundle package"
alias br='bundle exec rspec'
alias brs='bundle exec rspec'
alias bu="bundle update"
alias cat='ccat'
alias cdag="cd ~/source/ag"
alias cdagm="cd ~/source/ag_mobile_api"
alias cdagm='cd ~/source/ag_mobile_api'
alias cdags="cd ~/source/ag_sites"
alias cdb='cd ~/source/wp_blog_themes/Ag_Blog_Beta'
alias cdch='cd ~/source/christophestogo'
alias cdd='cd ~/source/dotfiles'
alias cddf=" cd ~/source/dotfiles"
alias cddt='cd ~/source/drawbridge_tester'
alias cdea="cd ~/source/hf/everest_api"
alias cdeo="cd ~/source/elastic_onesearch"
alias cdex="cd ~/source/ideo/excalibur"
alias cdgbr='cd ~/source/generator-bower-rjs'
alias cdgrf='cd ~/source/go/src/github.com/grafana/grafana'
alias cdhf="cd ~/source/hf/hikefinder"
alias cdi="cd ~/source/idg"
alias cdj='cd ~/source/json2yaml'
alias cdjqa='cd ~/source/jquery-autotagging'
alias cdl='cd ~/Downloads'
alias cdle="cd ~/source/leads"
alias cdlf="cd ~/source/lfender6445.github.io"
alias cdmch='cd ~/source/merchcat-aws'
alias cdmd="cd ~/source/m.apartmentguide"
alias cdmdr="cd ~/source/m.rent"
alias cdme="cd ~/source/metasaurus"
alias cdmn="cd ~/source/newhomeguide"
alias cdmr="cd ~/source/m.rentals"
alias cdn="cd ~/source/newhomeguide"
alias cdne="cd ~/source/newhomeguide"
alias cdnhg="cd ~/source/nhg_search"
alias cdns="cd ~/source/nhg_search"
alias cdo="cd ~/source/onesearch"
alias cdon="cd ~/source/onesearch.js"
alias cdot='cd ~/source/dotfiles'
alias cdp='cd ~/source/perf'
alias cdpr="cd ~/source/preserves"
alias cdre="cd ~/source/rent"
alias cdree='cd ~/source/realestateemails'
alias cdren="cd ~/source/rentals"
alias cds="cd ~/source"
alias cdsen='cd ~/source/senketsu'
alias cdt="cd ~/source/tuts"
alias cdt='cd ~/source/testmycss'
alias cdtb="cd ~/source/theme_bandit"
alias cdtmc='cd ~/source/testmycss'
alias cdtr="cd ~/source/trex"
alias cdz="cd ~/source/zutron"
alias ci='curl http://ag-web-01.ci.nor.primedia.com/ops/env/environment.cfg'
alias commiters="git shortlog -sn"
alias default_shell='chsh -s /bin/zsh'
alias elastic='elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml'
alias elastic='elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml'
alias elogin="curl 'http://170.140.98.93/cgi-bin/login' -H 'Pragma: no-cache' -H 'Origin: http://captive.web.emory.edu' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: no-cache' -H 'Referer: http://captive.web.emory.edu/hcp.php?cmd=login&switchip=170.140.98.93&mac=34:36:3b:cc:f0:d2&ip=172.24.68.194&essid=EHC%20Guest&url=http%3A%2F%2Fwww%2Ereddit%2Ecom%2F' -H 'Connection: keep-alive' --data 'email=nadamas%40gmail.com&Login=Log+In' --compressed"
alias g="git"
alias gaa="git add ."
alias gb="git branch"
alias gc="git co "
alias gca="git co ."
alias gcam="git commit --amend"
alias gcbw="gulp clean; gulp build; gulp watch"
alias gcd="git co dev"
alias gcf="git clean -f"
alias gcm="git co master"
alias gcn="git commit -m"
alias gcq="git co qa"
alias gd="git diff"
alias gdc="git diff --cached"
alias gemini='gem env; gem env gemdir'
alias gemm='bundle show'
alias gg='git show --pretty="format:" --name-only '
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glast="git diff HEAD~1 --stat"
alias gls="gl --name-status"
alias gmd="git merge dev"
alias gmm="git merge master"
alias gmt="git mergetool -t opendiff"
alias gpf="git push fork"
alias gphm="git push heroku master"
alias gpo="git push origin"
alias gpr="git pull --rebase"
alias gpt="git push --tags"
alias gs="git stash"
alias gsh="git show HEAD"
alias gsp="git stash pop"
alias gstory="git rev-parse --abbrev-ref HEAD | egrep -o '\d+'| head -n 1 | tr -d '\n' | pbcopy"
alias gtrack='git branch --set-upstream-to=origin/$(git rev-parse --abbrev-ref HEAD)'
alias history='history 25'
alias hosts='sudo vim /etc/hosts'
alias htd='cd /Applications/MAMP/htdocs/'
alias ip='ifconfig|grep inet|grep broadcast'
alias jbstart='/usr/local/Cellar/jboss-as/7.1.1.Final/libexec/bin/standalone.sh'
alias l='gl'
alias lock="less Gemfile.lock"
alias lock="less Gemfile.lock"
alias logst='logstash -f /usr/local/Cellar/logstash/1.4.1/logstash-simple.conf'
alias logst='logstash -f /usr/local/Cellar/logstash/1.4.1/logstash-simple.conf'
alias ls="ls -a"
alias mleak='tail -f /var/log/system.log'
alias myip="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias nameserver="cat /etc/resolv.conf"
alias ngconf="cd /usr/local/etc/nginx/sites"
alias ngconf='vim /etc/nginx/nginx.conf'
alias orig="find ./ -regex '.*\.\(orig\)'"
alias os="cat /etc/*-release"
alias pgconf="vim /var/lib/pgsql/9.4/data/pg_hba.conf"
alias pgs="pg_ctl -D /usr/local/var/postgres/ -l /usr/local/var/postgres/server.log start"
alias pgst="pg_ctl -D /usr/local/var/postgres/ stop -m 'fast'"
alias qa='curl http://ag-web-01.qa.nor.primedia.com/ops/env/environment.cfg'
alias qac='curl http://ag-web-01.qa.nor.primedia.com/ops/env/environment.cfg|pbcopy'
alias readm="less README.md"
alias readme="less README.md"
alias remove_all_example='find . -name "*.map" -exec rm -rf {} \;'
alias rprcheck='be rspec spec;rubocop;coffeelint app/assets/javascripts/*'
alias rubocop='rubocop --format simple'
alias s="git status"
alias sf='find . -type f|grep'
alias sprcheck='rt;rubocop;coffeelint app/assets/coffee/*'
alias sr='idg setup-repos'
alias src="source ~/.zshrc"
alias ss='idg start services'
alias sshconfig='vim ~/.ssh/config'
alias start_influx='influxdb -config=/usr/local/etc/influxdb.conf'
alias start_postgres='postgres -D /usr/local/var/postgres'
alias wrk='idg setup-repos; idg stop;idg start services'
alias zshrc="vim ~/.zshrc"
alias ios="open /Applications/Xcode.app/Contents/Applications/iOS\ Simulator.app"
alias reload!='. ~/.zshrc'
